### ISSUE TITLE
Matoucí nápis AKTUALIZUJTE

### ISSUE THREAD

**Issue by msusicky** [opendatalabcz/transparent-accounts#1]
URL:
https://transparentniucty.opendatalab.cz/ucty/0100/000123-3198300247
Nápis:
Prosím AKTUALIZUJTE účet.
AKTUALIZUJTE je modrý a na mobilu to svádí ke klikání. Nejde ale o odkaz.

**Comment by KasenX** [comment]
Fixed v 09e1add. Původně bylo v plánu přidat AKTUALIZUJTE funkčnost, ale v aktuálním řešení by to přineslo zbytečně moc komplexnosti. Byl tedy jenom upraven styling, aby nápis nepřipomínal odkaz.
